### ISSUE TITLE
Multiple runtime errors

### ISSUE THREAD

**Issue by antonio-fr** [NoRulesJustFeels/hicetnunc-minter-project#2]
On Windows 10 using NodeJS v16.13.0

```
$ npm run serve

> hen-minter@0.0.1 serve
> genversion src/version.js && webpack serve --mode=development

<w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:3000/
<i> [webpack-dev-server] On Your Network (IPv4): http://LO.C.AL.IP:3000/
<i> [webpack-dev-server] Content not from webpack is served from '<filepath>\hicetnunc-minter-project\dist' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
<i> [webpack-dev-middleware] wait until bundle finished: /
assets by path *.js 21 MiB
  asset index.bundle.js 20.8 MiB [emitted] (name: index)
  asset magick.js 139 KiB [emitted] [from: node_modules/wasm-imagemagick/dist/magick.js] [copied]
  asset node_modules_node-fetch_src_utils_multipart-parser_js.bundle.js 28.6 KiB [emitted]
assets by path *.wasm 6.38 MiB
  asset magick.wasm 4.01 MiB [emitted] [from: node_modules/wasm-imagemagick/dist/magick.wasm] [copied]
  asset MediaInfoModule.wasm 2.37 MiB [emitted] [from: node_modules/mediainfo.js/dist/MediaInfoModule.wasm] [copied]
asset assets/loading.gif 54.5 KiB [emitted] [from: public/assets/loading.gif] [copied]
asset index.html 16.4 KiB [emitted]
asset favicon.ico 1.12 KiB [emitted]
orphan modules 201 KiB [orphan] 105 modules
runtime modules 29.5 KiB 15 modules
modules by path ./node_modules/ 7.56 MiB
  javascript modules 7.41 MiB 1109 modules
  json modules 158 KiB 9 modules
modules by path ./src/*.js 103 KiB
  ./src/index.js 4.33 KiB [built] [code generated]
  ./src/minting.js 22.3 KiB [built] [code generated]
  + 10 modules
modules with errors 468 bytes [errors]
  optional modules 78 bytes [optional]
    node:process 39 bytes [optional] [built] [code generated] [1 error]
    node:stream/web 39 bytes [optional] [built] [code generated] [1 error]
  + 10 modules
+ 15 modules

WARNING in ./node_modules/node-domexception/index.js 5:31-56
Module not found: Error: Can't resolve 'worker_threads' in '<filepath>\hicetnunc-minter-project\node_modules\node-domexception'
 @ ./node_modules/fetch-blob/from.js 3:0-44 86:16-28
 @ ./node_modules/node-fetch/src/index.js 27:0-34:28 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/node-fetch/src/index.js 13:0-35 370:20-31 397:29-43 402:5-19 403:5-19
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:fs
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/fetch-blob/from.js 1:0-68 8:17-19 14:46-54 34:46-54 88:12-28
 @ ./node_modules/node-fetch/src/index.js 27:0-34:28 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:https
Module build failed: UnhandledSchemeError: Reading from "node:https" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/node-fetch/src/index.js 10:0-31 65:50-55
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:http
Module build failed: UnhandledSchemeError: Reading from "node:http" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\Hook.js:18:14)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
 @ ./node_modules/node-fetch/src/index.js 9:0-29 65:58-62
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:net
Module build failed: UnhandledSchemeError: Reading from "node:net" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/node-fetch/src/utils/referrer.js 1:0-30 109:23-27
 @ ./node_modules/node-fetch/src/index.js 26:0-66 225:37-66
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:path
Module build failed: UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/fetch-blob/from.js 2:0-36 50:5-13
 @ ./node_modules/node-fetch/src/index.js 27:0-34:28 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:process
Module build failed: UnhandledSchemeError: Reading from "node:process" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/fetch-blob/streams.cjs 10:20-43
 @ ./node_modules/fetch-blob/index.js 6:0-22
 @ ./node_modules/fetch-blob/from.js 6:0-29 37:48-52 100:0-69
 @ ./node_modules/node-fetch/src/index.js 27:0-34:28 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:stream/web
Module build failed: UnhandledSchemeError: Reading from "node:stream/web" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/fetch-blob/streams.cjs 14:32-58
 @ ./node_modules/fetch-blob/index.js 6:0-22
 @ ./node_modules/fetch-blob/from.js 6:0-29 37:48-52 100:0-69
 @ ./node_modules/node-fetch/src/index.js 27:0-34:28 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:stream
Module build failed: UnhandledSchemeError: Reading from "node:stream" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/node-fetch/src/index.js 12:0-66 72:47-62 211:83-98 248:14-18 248:34-45 298:11-15 312:16-20 312:36-47 320:13-17 326:13-17 349:11-15
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:url
Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/node-fetch/src/request.js 9:0-45 151:9-18
 @ ./node_modules/node-fetch/src/index.js 20:0-60 36:0-82 51:22-29 52:31-52 231:24-31
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:util
Module build failed: UnhandledSchemeError: Reading from "node:util" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/node-fetch/src/body.js 9:0-54 19:17-26 47:13-35 172:24-33 182:13-22 286:35-44 324:30-52
 @ ./node_modules/node-fetch/src/index.js 17:0-47 191:13-18 365:2-15
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

ERROR in node:zlib
Module build failed: UnhandledSchemeError: Reading from "node:zlib" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:827:25
    at Hook.eval [as callAsync] (eval at create (<filepath>\hicetnunc-minter-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:824:8)
    at processResource (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (<filepath>\hicetnunc-minter-project\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:814:3)
    at NormalModule.build (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:958:15)
    at <filepath>\hicetnunc-minter-project\node_modules\webpack\lib\Compilation.js:1370:12
    at NormalModule.needBuild (<filepath>\hicetnunc-minter-project\node_modules\webpack\lib\NormalModule.js:1247:32)
 @ ./node_modules/node-fetch/src/index.js 11:0-29 292:11-28 293:17-34 298:22-39 320:24-42 326:24-45 349:22-49
 @ ./node_modules/native-fetch/src/index.js 12:13-42 13:13-42 14:13-42 15:14-44
 @ ./node_modules/ipfs-utils/src/fetch.js 9:2-42
 @ ./node_modules/ipfs-utils/src/http/fetch.browser.js 4:55-74
 @ ./node_modules/ipfs-utils/src/http.js 4:36-59
 @ ./node_modules/ipfs-utils/src/files/url-source.js 3:13-31
 @ ./node_modules/ipfs-http-client/esm/src/index.js 123:0-125:44 123:0-125:44
 @ ./src/ipfs.js 44:0-42 82:19-25
 @ ./src/minting.js 37:0-34 519:33-54 545:31-47
 @ ./src/index.js 38:0-40 136:0-16 137:0-20

webpack 5.69.0 compiled with 12 errors and 1 warning in 15882 ms
```

Missing dependencies listed ? 
Bad Node version ?
MIssing .env custom options (not) filled by me ?

**Comment by antonio-fr** [comment]
I used` npm i --force` to install the dependencies, as the standard install is not working because of #1

**Comment by antonio-fr** [comment]
This issue is linked to the previous one, resolved with the npm lock file.
